import React, { useState } from 'react';
import { 
  Activity, 
  ArrowRight, 
  CheckCircle, 
  Building, 
  BedDouble, 
  Truck, 
  BrainCircuit,
  AlertTriangle
} from 'lucide-react';
import Layout from './Layout';
import styles from './Optimization.module.css';

const Optimization = () => {
  // --- MOCK MILP ENGINE STATE ---
  // In a real app, 'currentStep' would come from your backend
  const [currentStep, setCurrentStep] = useState(2); // Currently at Step 2 (Surge)
  
  // Your Specific 3-Step Protocol
  const steps = [
    { 
      id: 1, 
      title: 'Internal Reallocation', 
      desc: 'Optimize beds within the hospital', 
      isActive: currentStep >= 1,
      icon: BedDouble,
      color: 'blue'
    },
    { 
      id: 2, 
      title: 'Surge Capacity', 
      desc: 'Open overflow areas (Corridors/Halls)', 
      isActive: currentStep >= 2,
      icon: Building,
      color: 'orange'
    },
    { 
      id: 3, 
      title: 'External Transfer', 
      desc: 'Transfer patients to nearby hospitals', 
      isActive: currentStep >= 3,
      icon: Truck,
      color: 'gray'
    },
  ];

  // Recommendations generated by MILP
  const recommendations = [
    {
      id: 'REC-001',
      step: 1,
      type: 'Internal Flow',
      msg: 'Move 3 stable patients from ETU to General Ward 4 immediately.',
      impact: 'Reduces ETU load by 15%.',
      priority: 'High'
    },
    {
      id: 'REC-002',
      step: 2,
      type: 'Surge Activation',
      msg: 'Activate "Surge Area B" (Corridor) to accommodate 4 incoming ambulances.',
      impact: 'Prevents ambulance diversion.',
      priority: 'Critical'
    }
  ];

  return (
    <Layout activePage="Optimization">
      <div className={styles.container}>
        
        {/* --- HEADER --- */}
        <div className={styles.header}>
          <div>
            <h1 className={styles.title}>Optimization Engine</h1>
            <p className={styles.subtitle}>MILP-Driven Decision Support System</p>
          </div>
          <div className={styles.modelBadge}>
            <BrainCircuit size={18} />
            <span>MILP Model: <strong>Active (Step {currentStep})</strong></span>
          </div>
        </div>

        {/* --- SECTION 1: SYSTEM STATUS --- */}
        <div className={styles.statusCard}>
          <div className={styles.statusLeft}>
            <div className={styles.pulseContainer}>
              <div className={styles.pulseRing}></div>
              <Activity size={24} color="#dc2626" className={styles.pulseIcon} />
            </div>
            <div>
              <h3 className={styles.statusTitle}>Current Status: Escalation Required</h3>
              <p className={styles.statusDesc}>
                Deep Learning Model (TFT) predicts demand will exceed capacity in <strong>2 Hours</strong>.
                <br/>
                MILP Model has activated <strong>Step {currentStep}: Surge Capacity</strong>.
              </p>
            </div>
          </div>
        </div>

        {/* --- SECTION 2: 3-STEP VISUALIZATION --- */}
        <h3 className={styles.sectionTitle}>Optimization Protocol Execution</h3>
        <div className={styles.strategyGrid}>
          {steps.map((step, index) => (
            <div 
              key={step.id} 
              className={`${styles.stepCard} ${step.isActive ? styles.activeCard : styles.inactiveCard}`}
            >
              <div className={styles.stepHeader}>
                <span className={styles.stepNum}>Step 0{step.id}</span>
                {step.isActive && <span className={styles.activeBadge}>Active</span>}
              </div>
              
              <div className={styles.iconCircle} style={{backgroundColor: step.isActive ? '#eff6ff' : '#f3f4f6'}}>
                <step.icon size={24} color={step.isActive ? '#2563eb' : '#9ca3af'} />
              </div>

              <h4 className={styles.stepTitle}>{step.title}</h4>
              <p className={styles.stepDesc}>{step.desc}</p>

              {/* Connector Arrow */}
              {index < steps.length - 1 && (
                <div className={`${styles.connector} ${step.isActive ? styles.connectorActive : ''}`}>
                  <ArrowRight size={24} />
                </div>
              )}
            </div>
          ))}
        </div>

        {/* --- SECTION 3: GENERATED ACTIONS --- */}
        <h3 className={styles.sectionTitle}>Recommended Actions</h3>
        <div className={styles.recGrid}>
          {recommendations.map((rec) => (
            <div key={rec.id} className={styles.recCard}>
              <div className={styles.recHeader}>
                <span className={`${styles.priorityBadge} ${rec.priority === 'Critical' ? styles.critPrio : styles.highPrio}`}>
                  {rec.priority} Priority
                </span>
                <span className={styles.stepTag}>Step {rec.step} Protocol</span>
              </div>
              
              <div className={styles.recContent}>
                <h4 className={styles.recMsg}>{rec.msg}</h4>
                <div className={styles.impactBox}>
                  <CheckCircle size={16} color="#16a34a" />
                  <span><strong>Predicted Impact:</strong> {rec.impact}</span>
                </div>
              </div>

              <div className={styles.recActions}>
                <button className={styles.btnApprove}>Approve Action</button>
                <button className={styles.btnAnalyze}>Simulate</button>
              </div>
            </div>
          ))}
        </div>

      </div>
    </Layout>
  );
};

export default Optimization;